development:
  database: intraseec_tshirt_dev
  username: root
  password: admin
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock

test:
  database: intraseec_tshirt_test
  username: root
  password: admin
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock